/* Generated by tools/ops.py. Do not edit. */
#ifndef OPS_H
#define OPS_H

enum {
  OP_NUMBER, /* 36: ins [] outs ['Number'] execs [] */
  OP_VECTOR, /* 38: ins [] outs ['Vector'] execs [] */
  OP_ROTATION, /* 42: ins [] outs ['Rotation'] execs [] */
  OP_TRUE, /* 449: ins [] outs ['True'] execs [] */
  OP_FALSE, /* 451: ins [] outs ['False'] execs [] */
  OP_GET_VAR_NUM, /* 46: ins [] outs ['Number'] execs [] */
  OP_GET_VAR_VEC, /* 48: ins [] outs ['Vector'] execs [] */
  OP_GET_VAR_ROT, /* 50: ins [] outs ['Rotation'] execs [] */
  OP_GET_VAR_TRU, /* 52: ins [] outs ['Truth'] execs [] */
  OP_GET_VAR_OBJ, /* 54: ins [] outs ['Object'] execs [] */
  OP_GET_VAR_CON, /* 56: ins [] outs ['Constraint'] execs [] */
  OP_SET_VAR_NUM, /* 428: ins ['Value'] outs [] execs [] */
  OP_SET_VAR_VEC, /* 430: ins ['Value'] outs [] execs [] */
  OP_SET_VAR_ROT, /* 432: ins ['Value'] outs [] execs [] */
  OP_SET_VAR_TRU, /* 434: ins ['Value'] outs [] execs [] */
  OP_SET_VAR_OBJ, /* 436: ins ['Value'] outs [] execs [] */
  OP_SET_VAR_CON, /* 438: ins ['Value'] outs [] execs [] */
  OP_SET_PTR_NUM, /* 58: ins ['Variable', 'Value'] outs [] execs [] */
  OP_SET_PTR_VEC, /* 62: ins ['Variable', 'Value'] outs [] execs [] */
  OP_SET_PTR_ROT, /* 66: ins ['Variable', 'Value'] outs [] execs [] */
  OP_SET_PTR_TRU, /* 70: ins ['Variable', 'Value'] outs [] execs [] */
  OP_SET_PTR_OBJ, /* 74: ins ['Variable', 'Value'] outs [] execs [] */
  OP_SET_PTR_CON, /* 78: ins ['Variable', 'Value'] outs [] execs [] */
  OP_LIST_NUM, /* 82: ins ['Variable', 'Index'] outs ['Element'] execs [] */
  OP_LIST_OBJ, /* 86: ins ['Variable', 'Index'] outs ['Element'] execs [] */
  OP_LIST_VEC, /* 461: ins ['Variable', 'Index'] outs ['Element'] execs [] */
  OP_LIST_ROT, /* 465: ins ['Variable', 'Index'] outs ['Element'] execs [] */
  OP_LIST_TRU, /* 469: ins ['Variable', 'Index'] outs ['Element'] execs [] */
  OP_LIST_CON, /* 473: ins ['Variable', 'Index'] outs ['Element'] execs [] */
  OP_INCREASE_NUMBER, /* 556: ins ['Variable'] outs [] execs [] */
  OP_DECREASE_NUMBER, /* 558: ins ['Variable'] outs [] execs [] */
  OP_NEGATE, /* 90: ins ['Num'] outs ['-Num'] execs [] */
  OP_ADD_NUMBERS, /* 92: ins ['Num1', 'Num2'] outs ['Num1 + Num2'] execs [] */
  OP_ADD_VECTORS, /* 96: ins ['Vec1', 'Vec2'] outs ['Vec1 + Vec2'] execs [] */
  OP_SUBTRACT_NUMBERS, /* 100: ins ['Num1', 'Num2'] outs ['Num1 - Num2'] execs [] */
  OP_SUBTRACT_VECTORS, /* 104: ins ['Vec1', 'Vec2'] outs ['Vec1 - Vec2'] execs [] */
  OP_MULTIPLY, /* 108: ins ['Num1', 'Num2'] outs ['Num1 * Num2'] execs [] */
  OP_SCALE, /* 112: ins ['Vec', 'Num'] outs ['Vec * Num'] execs [] */
  OP_ROTATE, /* 116: ins ['Vec', 'Rot'] outs ['Rot * Vec'] execs [] */
  OP_COMBINE, /* 120: ins ['Rot1', 'Rot2'] outs ['Rot1 * Rot2'] execs [] */
  OP_DIVIDE, /* 124: ins ['Num1', 'Num2'] outs ['Num1 / Num2'] execs [] */
  OP_LESS_THAN, /* 128: ins ['Num1', 'Num2'] outs ['Num1 < Num2'] execs [] */
  OP_EQUALS_NUMBERS, /* 132: ins ['Num1', 'Num2'] outs ['Num1 = Num2'] execs [] */
  OP_EQUALS_VECTORS, /* 136: ins ['Vec1', 'Vec2'] outs ['Vec1 = Vec2'] execs [] */
  OP_EQUALS_OBJECTS, /* 140: ins ['Obj1', 'Obj2'] outs ['Obj1 = Obj2'] execs [] */
  OP_NOT, /* 144: ins ['Tru'] outs ['Not Tru'] execs [] */
  OP_AND, /* 146: ins ['Tru1', 'Tru2'] outs ['Tru1 & Tru2'] execs [] */
  OP_MAKE_VECTOR, /* 150: ins ['X', 'Y', 'Z'] outs ['Vector'] execs [] */
  OP_BREAK_VECTOR, /* 156: ins ['Vector'] outs ['X', 'Y', 'Z'] execs [] */
  OP_MAKE_ROTATION, /* 162: ins ['X angle', 'Y angle', 'Z angle'] outs ['Rotation'] execs [] */
  OP_RANDOM, /* 168: ins ['Min', 'Max'] outs ['Random'] execs [] */
  OP_MODULO, /* 172: ins ['a', 'b'] outs ['mod(a,b)'] execs [] */
  OP_MIN, /* 176: ins ['Num1', 'Num2'] outs ['Smaller'] execs [] */
  OP_MAX, /* 180: ins ['Num1', 'Num2'] outs ['Bigger'] execs [] */
  OP_ROUND, /* 184: ins ['Number'] outs ['Rounded'] execs [] */
  OP_FLOOR, /* 186: ins ['Number'] outs ['Floor'] execs [] */
  OP_CEILING, /* 188: ins ['Number'] outs ['Ceiling'] execs [] */
  OP_DISTANCE, /* 190: ins ['Vector', 'Vector'] outs ['Distance'] execs [] */
  OP_LERP, /* 194: ins ['From', 'To', 'Amount'] outs ['Rotation'] execs [] */
  OP_AXIS_ANGLE, /* 200: ins ['Axis', 'Angle'] outs ['Rotation'] execs [] */
  OP_LOOK_ROTATION, /* 204: ins ['Direction', 'Up'] outs ['Rotation'] execs [] */
  OP_LINE_VS_PLANE, /* 208: ins ['Line From', 'Line To', 'Plane Point', 'Plane Normal'] outs ['Intersection'] execs [] */
  OP_SIN, /* 413: ins ['Num'] outs ['Sin(Num)'] execs [] */
  OP_OR, /* 417: ins ['Tru1', 'Tru2'] outs ['Tru1 | Tru2'] execs [] */
  OP_EQUALS_TRUTHS, /* 421: ins ['Tru1', 'Tru2'] outs ['Tru1 = Tru2'] execs [] */
  OP_INVERSE, /* 440: ins ['Rot'] outs ['Rot Inverse'] execs [] */
  OP_BREAK_ROTATION, /* 442: ins ['Rotation'] outs ['X angle', 'Y angle', 'Z angle'] execs [] */
  OP_COS, /* 453: ins ['Num'] outs ['Cos(Num)'] execs [] */
  OP_ABSOLUTE, /* 455: ins ['Num'] outs ['|Num|'] execs [] */
  OP_POWER, /* 457: ins ['Base', 'Exponent'] outs ['Base ^ Exponent'] execs [] */
  OP_GREATER_THAN, /* 481: ins ['Num1', 'Num2'] outs ['Num1 > Num2'] execs [] */
  OP_DOT_PRODUCT, /* 570: ins ['Vector', 'Vector'] outs ['Dot Product'] execs [] */
  OP_CROSS_PRODUCT, /* 574: ins ['Vector', 'Vector'] outs ['Cross Product'] execs [] */
  OP_NORMALIZE, /* 578: ins ['Vector'] outs ['Normalized'] execs [] */
  OP_LOGARITHM, /* 580: ins ['Number', 'Base'] outs ['Logarithm'] execs [] */
  OP_SCREEN_TO_WORLD, /* 216: ins ['Screen X', 'Screen Y'] outs ['World Near', 'World Far'] execs [] */
  OP_SCREEN_SIZE, /* 220: ins [] outs ['Width', 'Height'] execs [] */
  OP_ACCELEROMETER, /* 224: ins [] outs ['Direction'] execs [] */
  OP_WORLD_TO_SCREEN, /* 477: ins ['World Pos'] outs ['Screen X', 'Screen Y'] execs [] */
  OP_CURRENT_FRAME, /* 564: ins [] outs ['Counter'] execs [] */
  OP_RAYCAST, /* 228: ins ['From', 'To'] outs ['Hit?', 'Hit Pos', 'Hit Obj'] execs [] */
  OP_GET_POSITION, /* 278: ins ['Object'] outs ['Position', 'Rotation'] execs [] */
  OP_GET_VELOCITY, /* 288: ins ['Object'] outs ['Velocity', 'Spin'] execs [] */
  OP_GET_SIZE, /* 489: ins ['Object'] outs ['Min', 'Max'] execs [] */
  OP_IF, /* 234: ins ['Condition'] outs [] execs ['True', 'False'] */
  OP_PLAY_SENSOR, /* 238: ins [] outs [] execs ['On Play'] */
  OP_TOUCH_SENSOR, /* 242: ins [] outs ['Screen X', 'Screen Y'] execs ['Touched'] */
  OP_SWIPE_SENSOR, /* 248: ins [] outs ['Direction'] execs ['Swiped'] */
  OP_LATE_UPDATE, /* 566: ins [] outs [] execs ['After Physics'] */
  OP_BOX_ART_SENSOR, /* 409: ins [] outs [] execs ['On Screenshot'] */
  OP_BUTTON, /* 588: ins [] outs [] execs ['Button'] */
  OP_JOYSTICK, /* 592: ins [] outs ['Joy Dir'] execs [] */
  OP_COLLISION, /* 401: ins ['1st Object'] outs ['2nd Object', 'Impulse', 'Normal'] execs ['Collided'] */
  OP_LOOP, /* 560: ins ['Start', 'Stop'] outs ['Counter'] execs ['Do'] */
  OP_WIN, /* 252: ins [] outs [] execs [] */
  OP_LOSE, /* 256: ins [] outs [] execs [] */
  OP_SET_SCORE, /* 260: ins ['Score', 'Coins'] outs [] execs [] */
  OP_SET_CAMERA, /* 268: ins ['Position', 'Rotation', 'Range'] outs [] execs [] */
  OP_SET_LIGHT, /* 274: ins ['Position', 'Rotation'] outs [] execs [] */
  OP_SET_POSITION, /* 282: ins ['Object', 'Position', 'Rotation'] outs [] execs [] */
  OP_SET_VELOCITY, /* 292: ins ['Object', 'Velocity', 'Spin'] outs [] execs [] */
  OP_ADD_FORCE, /* 298: ins ['Object', 'Force', 'Apply at', 'Torque'] outs [] execs [] */
  OP_SET_VISIBLE, /* 306: ins ['Object', 'Visible'] outs [] execs [] */
  OP_SET_LOCKED, /* 310: ins ['Object', 'Position', 'Rotation'] outs [] execs [] */
  OP_CREATE_OBJECT, /* 316: ins ['Object'] outs ['Copy'] execs [] */
  OP_DESTROY_OBJECT, /* 320: ins ['Object'] outs [] execs [] */
  OP_SET_GRAVITY, /* 324: ins ['Gravity'] outs [] execs [] */
  OP_SET_MASS, /* 328: ins ['Object', 'Mass'] outs [] execs [] */
  OP_SET_FRICTION, /* 332: ins ['Object', 'Friction'] outs [] execs [] */
  OP_SET_BOUNCINESS, /* 336: ins ['Object', 'Bounciness'] outs [] execs [] */
  OP_ADD_CONSTRAINT, /* 340: ins ['Base', 'Part', 'Pivot'] outs ['Constraint'] execs [] */
  OP_LINEAR_LIMITS, /* 346: ins ['Constraint', 'Lower', 'Upper'] outs [] execs [] */
  OP_ANGULAR_LIMITS, /* 352: ins ['Constraint', 'Lower', 'Upper'] outs [] execs [] */
  OP_LINEAR_SPRING, /* 358: ins ['Constraint', 'Stiffness', 'Damping'] outs [] execs [] */
  OP_ANGULAR_SPRING, /* 364: ins ['Constraint', 'Stiffness', 'Damping'] outs [] execs [] */
  OP_LINEAR_MOTOR, /* 370: ins ['Constraint', 'Speed', 'Force'] outs [] execs [] */
  OP_ANGULAR_MOTOR, /* 376: ins ['Constraint', 'Speed', 'Force'] outs [] execs [] */
  OP_PLAY_SOUND, /* 264: ins ['Volume', 'Pitch'] outs ['Channel'] execs [] */
  OP_VOLUME_PITCH, /* 391: ins ['Channel', 'Volume', 'Pitch'] outs [] execs [] */
  OP_STOP_SOUND, /* 397: ins ['Channel'] outs [] execs [] */
  OP_RANDOM_SEED, /* 485: ins ['Seed'] outs [] execs [] */
  OP_INSPECT_16, /* 16: ins ['Number'] outs [] execs [] */
  OP_INSPECT_20, /* 20: ins ['Vector'] outs [] execs [] */
  OP_INSPECT_24, /* 24: ins ['Rotation'] outs [] execs [] */
  OP_INSPECT_28, /* 28: ins ['Truth'] outs [] execs [] */
  OP_INSPECT_32, /* 32: ins ['Object'] outs [] execs [] */
  OP_CUSTOM,
  OP_COUNT
};

/* per op: number of value inputs, value outputs, extra exec outputs, flags (1 = active) */
static const unsigned char op_shape[OP_COUNT][4] = {
  {0, 1, 0, 0}, /* Number */
  {0, 1, 0, 0}, /* Vector */
  {0, 1, 0, 0}, /* Rotation */
  {0, 1, 0, 0}, /* True */
  {0, 1, 0, 0}, /* False */
  {0, 1, 0, 0}, /* Variable */
  {0, 1, 0, 0}, /* Variable */
  {0, 1, 0, 0}, /* Variable */
  {0, 1, 0, 0}, /* Variable */
  {0, 1, 0, 0}, /* Variable */
  {0, 1, 0, 0}, /* Variable */
  {1, 0, 0, 1}, /* Set Variable */
  {1, 0, 0, 1}, /* Set Variable */
  {1, 0, 0, 1}, /* Set Variable */
  {1, 0, 0, 1}, /* Set Variable */
  {1, 0, 0, 1}, /* Set Variable */
  {1, 0, 0, 1}, /* Set Variable */
  {2, 0, 0, 1}, /* Set Number */
  {2, 0, 0, 1}, /* Set Vector */
  {2, 0, 0, 1}, /* Set Rotation */
  {2, 0, 0, 1}, /* Set Truth */
  {2, 0, 0, 1}, /* Set Object */
  {2, 0, 0, 1}, /* Set Constraint */
  {2, 1, 0, 0}, /* List Number */
  {2, 1, 0, 0}, /* List Object */
  {2, 1, 0, 0}, /* List Vector */
  {2, 1, 0, 0}, /* List Rotation */
  {2, 1, 0, 0}, /* List Truth */
  {2, 1, 0, 0}, /* List Constraint */
  {1, 0, 0, 1}, /* Increase Number */
  {1, 0, 0, 1}, /* Decrease Number */
  {1, 1, 0, 0}, /* Negate */
  {2, 1, 0, 0}, /* Add Numbers */
  {2, 1, 0, 0}, /* Add Vectors */
  {2, 1, 0, 0}, /* Subtract Numbers */
  {2, 1, 0, 0}, /* Subtract Vectors */
  {2, 1, 0, 0}, /* Multiply */
  {2, 1, 0, 0}, /* Scale */
  {2, 1, 0, 0}, /* Rotate */
  {2, 1, 0, 0}, /* Combine */
  {2, 1, 0, 0}, /* Divide */
  {2, 1, 0, 0}, /* Less Than */
  {2, 1, 0, 0}, /* Equals Numbers */
  {2, 1, 0, 0}, /* Equals Vectors */
  {2, 1, 0, 0}, /* Equals Objects */
  {1, 1, 0, 0}, /* Not */
  {2, 1, 0, 0}, /* AND */
  {3, 1, 0, 0}, /* Make Vector */
  {1, 3, 0, 0}, /* Break Vector */
  {3, 1, 0, 0}, /* Make Rotation */
  {2, 1, 0, 0}, /* Random */
  {2, 1, 0, 0}, /* Modulo */
  {2, 1, 0, 0}, /* Min */
  {2, 1, 0, 0}, /* Max */
  {1, 1, 0, 0}, /* Round */
  {1, 1, 0, 0}, /* Floor */
  {1, 1, 0, 0}, /* Ceiling */
  {2, 1, 0, 0}, /* Distance */
  {3, 1, 0, 0}, /* LERP */
  {2, 1, 0, 0}, /* Axis Angle */
  {2, 1, 0, 0}, /* Look Rotation */
  {4, 1, 0, 0}, /* Line vs Plane */
  {1, 1, 0, 0}, /* Sin */
  {2, 1, 0, 0}, /* OR */
  {2, 1, 0, 0}, /* Equals Truths */
  {1, 1, 0, 0}, /* Inverse */
  {1, 3, 0, 0}, /* Break Rotation */
  {1, 1, 0, 0}, /* Cos */
  {1, 1, 0, 0}, /* Absolute */
  {2, 1, 0, 0}, /* Power */
  {2, 1, 0, 0}, /* Greater Than */
  {2, 1, 0, 0}, /* Dot Product */
  {2, 1, 0, 0}, /* Cross Product */
  {1, 1, 0, 0}, /* Normalize */
  {2, 1, 0, 0}, /* Logarithm */
  {2, 2, 0, 0}, /* Screen To World */
  {0, 2, 0, 0}, /* Screen Size */
  {0, 1, 0, 0}, /* Accelerometer */
  {1, 2, 0, 0}, /* World To Screen */
  {0, 1, 0, 0}, /* Current Frame */
  {2, 3, 0, 0}, /* Raycast */
  {1, 2, 0, 0}, /* Get Position */
  {1, 2, 0, 0}, /* Get Velocity */
  {1, 2, 0, 0}, /* Get Size */
  {1, 0, 2, 1}, /* If */
  {0, 0, 1, 1}, /* Play Sensor */
  {0, 2, 1, 1}, /* Touch Sensor */
  {0, 1, 1, 1}, /* Swipe Sensor */
  {0, 0, 1, 1}, /* Late Update */
  {0, 0, 1, 1}, /* Box Art Sensor */
  {0, 0, 1, 1}, /* Button */
  {0, 1, 0, 1}, /* Joystick */
  {1, 3, 1, 1}, /* Collision */
  {2, 1, 1, 1}, /* Loop */
  {0, 0, 0, 1}, /* Win */
  {0, 0, 0, 1}, /* Lose */
  {2, 0, 0, 1}, /* Set Score */
  {3, 0, 0, 1}, /* Set Camera */
  {2, 0, 0, 1}, /* Set Light */
  {3, 0, 0, 1}, /* Set Position */
  {3, 0, 0, 1}, /* Set Velocity */
  {4, 0, 0, 1}, /* Add Force */
  {2, 0, 0, 1}, /* Set Visible */
  {3, 0, 0, 1}, /* Set Locked */
  {1, 1, 0, 1}, /* Create Object */
  {1, 0, 0, 1}, /* Destroy Object */
  {1, 0, 0, 1}, /* Set Gravity */
  {2, 0, 0, 1}, /* Set Mass */
  {2, 0, 0, 1}, /* Set Friction */
  {2, 0, 0, 1}, /* Set Bounciness */
  {3, 1, 0, 1}, /* Add Constraint */
  {3, 0, 0, 1}, /* Linear Limits */
  {3, 0, 0, 1}, /* Angular Limits */
  {3, 0, 0, 1}, /* Linear Spring */
  {3, 0, 0, 1}, /* Angular Spring */
  {3, 0, 0, 1}, /* Linear Motor */
  {3, 0, 0, 1}, /* Angular Motor */
  {2, 1, 0, 1}, /* Play Sound */
  {3, 0, 0, 1}, /* Volume Pitch */
  {1, 0, 0, 1}, /* Stop Sound */
  {1, 0, 0, 1}, /* Random Seed */
  {1, 0, 0, 1}, /* Inspect Number */
  {1, 0, 0, 1}, /* Inspect Vector */
  {1, 0, 0, 1}, /* Inspect Rotation */
  {1, 0, 0, 1}, /* Inspect Truth */
  {1, 0, 0, 1}, /* Inspect Object */
  {0, 0, 0, 1}, /* custom */
};

#endif
